version: "3.8"

services:
  app:
    build:
      context: .
      target: builder # Use the builder stage for development
    ports:
      - "3000:3000" # API port
      - "9001:9001" # nREPL port
    volumes:
      - .:/build # Mount source code for live reloading
      - ~/.m2:/root/.m2 # Cache Maven dependencies
      - ~/.aws:/root/.aws:ro # Mount AWS credentials (read-only)
    environment:
      - AWS_REGION=us-west-2
      - WAREHOUSE_BUCKET=s3://your-bucket/warehouse # Override in .env
    command: clj -M:run
    # Keep container running for development
    stdin_open: true
    tty: true
